<?php

use Illuminate\Database\Seeder;
use App\Region;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
    Region::truncate();

		$countries = array(
			array('id' => 1,'shortname' => 'AF' ,'name' => "Afghanistan",'phonecode' => 93,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 2,'shortname' => 'AL' ,'name' => "Albania",'phonecode' => 355,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 3,'shortname' => 'DZ' ,'name' => "Algeria",'phonecode' => 213,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 4,'shortname' => 'AS' ,'name' => "American Samoa",'phonecode' => 1684,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 5,'shortname' => 'AD' ,'name' => "Andorra",'phonecode' => 376,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 6,'shortname' => 'AO' ,'name' => "Angola",'phonecode' => 244,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 7,'shortname' => 'AI' ,'name' => "Anguilla",'phonecode' => 1264,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 8,'shortname' => 'AQ' ,'name' => "Antarctica",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 9,'shortname' => 'AG' ,'name' => "Antigua And Barbuda",'phonecode' => 1268,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 10,'shortname' => 'AR','name' => "Argentina",'phonecode' => 54,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 11,'shortname' => 'AM','name' => "Armenia",'phonecode' => 374,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 12,'shortname' => 'AW','name' => "Aruba",'phonecode' => 297,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 13,'shortname' => 'AU','name' => "Australia",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 14,'shortname' => 'AT','name' => "Austria",'phonecode' => 43,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 15,'shortname' => 'AZ','name' => "Azerbaijan",'phonecode' => 994,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 16,'shortname' => 'BS','name' => "Bahamas The",'phonecode' => 1242,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 17,'shortname' => 'BH','name' => "Bahrain",'phonecode' => 973,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 18,'shortname' => 'BD','name' => "Bangladesh",'phonecode' => 880,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 19,'shortname' => 'BB','name' => "Barbados",'phonecode' => 1246,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 20,'shortname' => 'BY','name' => "Belarus",'phonecode' => 375,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 21,'shortname' => 'BE','name' => "Belgium",'phonecode' => 32,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 22,'shortname' => 'BZ','name' => "Belize",'phonecode' => 501,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 23,'shortname' => 'BJ','name' => "Benin",'phonecode' => 229,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 24,'shortname' => 'BM','name' => "Bermuda",'phonecode' => 1441,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 25,'shortname' => 'BT','name' => "Bhutan",'phonecode' => 975,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 26,'shortname' => 'BO','name' => "Bolivia",'phonecode' => 591,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 27,'shortname' => 'BA','name' => "Bosnia and Herzegovina",'phonecode' => 387,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 28,'shortname' => 'BW','name' => "Botswana",'phonecode' => 267,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 29,'shortname' => 'BV','name' => "Bouvet Island",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 30,'shortname' => 'BR','name' => "Brazil",'phonecode' => 55,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 31,'shortname' => 'IO','name' => "British Indian Ocean Territory",'phonecode' => 246,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 32,'shortname' => 'BN','name' => "Brunei",'phonecode' => 673,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 33,'shortname' => 'BG','name' => "Bulgaria",'phonecode' => 359,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 34,'shortname' => 'BF','name' => "Burkina Faso",'phonecode' => 226,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 35,'shortname' => 'BI','name' => "Burundi",'phonecode' => 257,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 36,'shortname' => 'KH','name' => "Cambodia",'phonecode' => 855,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 37,'shortname' => 'CM','name' => "Cameroon",'phonecode' => 237,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 38,'shortname' => 'CA','name' => "Canada",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 39,'shortname' => 'CV','name' => "Cape Verde",'phonecode' => 238,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 40,'shortname' => 'KY','name' => "Cayman Islands",'phonecode' => 1345,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 41,'shortname' => 'CF','name' => "Central African Republic",'phonecode' => 236,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 42,'shortname' => 'TD','name' => "Chad",'phonecode' => 235,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 43,'shortname' => 'CL','name' => "Chile",'phonecode' => 56,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 44,'shortname' => 'CN','name' => "China",'phonecode' => 86,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 45,'shortname' => 'CX','name' => "Christmas Island",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 46,'shortname' => 'CC','name' => "Cocos (Keeling) Islands",'phonecode' => 672,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 47,'shortname' => 'CO','name' => "Colombia",'phonecode' => 57,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 48,'shortname' => 'KM','name' => "Comoros",'phonecode' => 269,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 49,'shortname' => 'CG','name' => "Congo",'phonecode' => 242,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 50,'shortname' => 'CD','name' => "Congo The Democratic Republic Of The",'phonecode' => 242,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 51,'shortname' => 'CK','name' => "Cook Islands",'phonecode' => 682,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 52,'shortname' => 'CR','name' => "Costa Rica",'phonecode' => 506,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 53,'shortname' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 54,'shortname' => 'HR','name' => "Croatia (Hrvatska)",'phonecode' => 385,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 55,'shortname' => 'CU','name' => "Cuba",'phonecode' => 53,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 56,'shortname' => 'CY','name' => "Cyprus",'phonecode' => 357,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 57,'shortname' => 'CZ','name' => "Czech Republic",'phonecode' => 420,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 58,'shortname' => 'DK','name' => "Denmark",'phonecode' => 45,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 59,'shortname' => 'DJ','name' => "Djibouti",'phonecode' => 253,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 60,'shortname' => 'DM','name' => "Dominica",'phonecode' => 1767,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 61,'shortname' => 'DO','name' => "Dominican Republic",'phonecode' => 1809,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 62,'shortname' => 'TP','name' => "East Timor",'phonecode' => 670,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 63,'shortname' => 'EC','name' => "Ecuador",'phonecode' => 593,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 64,'shortname' => 'EG','name' => "Egypt",'phonecode' => 20,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 65,'shortname' => 'SV','name' => "El Salvador",'phonecode' => 503,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 66,'shortname' => 'GQ','name' => "Equatorial Guinea",'phonecode' => 240,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 67,'shortname' => 'ER','name' => "Eritrea",'phonecode' => 291,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 68,'shortname' => 'EE','name' => "Estonia",'phonecode' => 372,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 69,'shortname' => 'ET','name' => "Ethiopia",'phonecode' => 251,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 70,'shortname' => 'XA','name' => "External Territories of Australia",'phonecode' => 61,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 71,'shortname' => 'FK','name' => "Falkland Islands",'phonecode' => 500,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 72,'shortname' => 'FO','name' => "Faroe Islands",'phonecode' => 298,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 73,'shortname' => 'FJ','name' => "Fiji Islands",'phonecode' => 679,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 74,'shortname' => 'FI','name' => "Finland",'phonecode' => 358,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 75,'shortname' => 'FR','name' => "France",'phonecode' => 33,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 76,'shortname' => 'GF','name' => "French Guiana",'phonecode' => 594,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 77,'shortname' => 'PF','name' => "French Polynesia",'phonecode' => 689,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 78,'shortname' => 'TF','name' => "French Southern Territories",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 79,'shortname' => 'GA','name' => "Gabon",'phonecode' => 241,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 80,'shortname' => 'GM','name' => "Gambia The",'phonecode' => 220,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 81,'shortname' => 'GE','name' => "Georgia",'phonecode' => 995,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 82,'shortname' => 'DE','name' => "Germany",'phonecode' => 49,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 83,'shortname' => 'GH','name' => "Ghana",'phonecode' => 233,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 84,'shortname' => 'GI','name' => "Gibraltar",'phonecode' => 350,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 85,'shortname' => 'GR','name' => "Greece",'phonecode' => 30,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 86,'shortname' => 'GL','name' => "Greenland",'phonecode' => 299,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 87,'shortname' => 'GD','name' => "Grenada",'phonecode' => 1473,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 88,'shortname' => 'GP','name' => "Guadeloupe",'phonecode' => 590,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 89,'shortname' => 'GU','name' => "Guam",'phonecode' => 1671,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 90,'shortname' => 'GT','name' => "Guatemala",'phonecode' => 502,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 91,'shortname' => 'XU','name' => "Guernsey and Alderney",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 92,'shortname' => 'GN','name' => "Guinea",'phonecode' => 224,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 93,'shortname' => 'GW','name' => "Guinea-Bissau",'phonecode' => 245,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 94,'shortname' => 'GY','name' => "Guyana",'phonecode' => 592,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 95,'shortname' => 'HT','name' => "Haiti",'phonecode' => 509,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 96,'shortname' => 'HM','name' => "Heard and McDonald Islands",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 97,'shortname' => 'HN','name' => "Honduras",'phonecode' => 504,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 98,'shortname' => 'HK','name' => "Hong Kong S.A.R.",'phonecode' => 852,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 99,'shortname' => 'HU','name' => "Hungary",'phonecode' => 36,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 100,'shortname' => 'IS','name' => "Iceland",'phonecode' => 354,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 101,'shortname' => 'IN','name' => "India",'phonecode' => 91,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 102,'shortname' => 'ID','name' => "Indonesia",'phonecode' => 62,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 103,'shortname' => 'IR','name' => "Iran",'phonecode' => 98,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 104,'shortname' => 'IQ','name' => "Iraq",'phonecode' => 964,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 105,'shortname' => 'IE','name' => "Ireland",'phonecode' => 353,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 106,'shortname' => 'IL','name' => "Israel",'phonecode' => 972,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 107,'shortname' => 'IT','name' => "Italy",'phonecode' => 39,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 108,'shortname' => 'JM','name' => "Jamaica",'phonecode' => 1876,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 109,'shortname' => 'JP','name' => "Japan",'phonecode' => 81,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 110,'shortname' => 'XJ','name' => "Jersey",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 111,'shortname' => 'JO','name' => "Jordan",'phonecode' => 962,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 112,'shortname' => 'KZ','name' => "Kazakhstan",'phonecode' => 7,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 113,'shortname' => 'KE','name' => "Kenya",'phonecode' => 254,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 114,'shortname' => 'KI','name' => "Kiribati",'phonecode' => 686,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 115,'shortname' => 'KP','name' => "Korea North",'phonecode' => 850,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 116,'shortname' => 'KR','name' => "Korea South",'phonecode' => 82,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 117,'shortname' => 'KW','name' => "Kuwait",'phonecode' => 965,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 118,'shortname' => 'KG','name' => "Kyrgyzstan",'phonecode' => 996,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 119,'shortname' => 'LA','name' => "Laos",'phonecode' => 856,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 120,'shortname' => 'LV','name' => "Latvia",'phonecode' => 371,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 121,'shortname' => 'LB','name' => "Lebanon",'phonecode' => 961,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 122,'shortname' => 'LS','name' => "Lesotho",'phonecode' => 266,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 123,'shortname' => 'LR','name' => "Liberia",'phonecode' => 231,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 124,'shortname' => 'LY','name' => "Libya",'phonecode' => 218,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 125,'shortname' => 'LI','name' => "Liechtenstein",'phonecode' => 423,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 126,'shortname' => 'LT','name' => "Lithuania",'phonecode' => 370,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 127,'shortname' => 'LU','name' => "Luxembourg",'phonecode' => 352,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 128,'shortname' => 'MO','name' => "Macau S.A.R.",'phonecode' => 853,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 129,'shortname' => 'MK','name' => "Macedonia",'phonecode' => 389,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 130,'shortname' => 'MG','name' => "Madagascar",'phonecode' => 261,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 131,'shortname' => 'MW','name' => "Malawi",'phonecode' => 265,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 132,'shortname' => 'MY','name' => "Malaysia",'phonecode' => 60,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 133,'shortname' => 'MV','name' => "Maldives",'phonecode' => 960,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 134,'shortname' => 'ML','name' => "Mali",'phonecode' => 223,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 135,'shortname' => 'MT','name' => "Malta",'phonecode' => 356,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 136,'shortname' => 'XM','name' => "Man (Isle of)",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 137,'shortname' => 'MH','name' => "Marshall Islands",'phonecode' => 692,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 138,'shortname' => 'MQ','name' => "Martinique",'phonecode' => 596,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 139,'shortname' => 'MR','name' => "Mauritania",'phonecode' => 222,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 140,'shortname' => 'MU','name' => "Mauritius",'phonecode' => 230,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 141,'shortname' => 'YT','name' => "Mayotte",'phonecode' => 269,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 142,'shortname' => 'MX','name' => "Mexico",'phonecode' => 52,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 143,'shortname' => 'FM','name' => "Micronesia",'phonecode' => 691,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 144,'shortname' => 'MD','name' => "Moldova",'phonecode' => 373,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 145,'shortname' => 'MC','name' => "Monaco",'phonecode' => 377,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 146,'shortname' => 'MN','name' => "Mongolia",'phonecode' => 976,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 147,'shortname' => 'MS','name' => "Montserrat",'phonecode' => 1664,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 148,'shortname' => 'MA','name' => "Morocco",'phonecode' => 212,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 149,'shortname' => 'MZ','name' => "Mozambique",'phonecode' => 258,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 150,'shortname' => 'MM','name' => "Myanmar",'phonecode' => 95,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 151,'shortname' => 'NA','name' => "Namibia",'phonecode' => 264,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 152,'shortname' => 'NR','name' => "Nauru",'phonecode' => 674,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 153,'shortname' => 'NP','name' => "Nepal",'phonecode' => 977,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 154,'shortname' => 'AN','name' => "Netherlands Antilles",'phonecode' => 599,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 155,'shortname' => 'NL','name' => "Netherlands The",'phonecode' => 31,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 156,'shortname' => 'NC','name' => "New Caledonia",'phonecode' => 687,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 157,'shortname' => 'NZ','name' => "New Zealand",'phonecode' => 64,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 158,'shortname' => 'NI','name' => "Nicaragua",'phonecode' => 505,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 159,'shortname' => 'NE','name' => "Niger",'phonecode' => 227,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 160,'shortname' => 'NG','name' => "Nigeria",'phonecode' => 234,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 161,'shortname' => 'NU','name' => "Niue",'phonecode' => 683,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 162,'shortname' => 'NF','name' => "Norfolk Island",'phonecode' => 672,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 163,'shortname' => 'MP','name' => "Northern Mariana Islands",'phonecode' => 1670,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 164,'shortname' => 'NO','name' => "Norway",'phonecode' => 47,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 165,'shortname' => 'OM','name' => "Oman",'phonecode' => 968,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 166,'shortname' => 'PK','name' => "Pakistan",'phonecode' => 92,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 167,'shortname' => 'PW','name' => "Palau",'phonecode' => 680,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 168,'shortname' => 'PS','name' => "Palestinian Territory Occupied",'phonecode' => 970,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 169,'shortname' => 'PA','name' => "Panama",'phonecode' => 507,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 170,'shortname' => 'PG','name' => "Papua new Guinea",'phonecode' => 675,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 171,'shortname' => 'PY','name' => "Paraguay",'phonecode' => 595,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 172,'shortname' => 'PE','name' => "Peru",'phonecode' => 51,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 173,'shortname' => 'PH','name' => "Philippines",'phonecode' => 63,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 174,'shortname' => 'PN','name' => "Pitcairn Island",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 175,'shortname' => 'PL','name' => "Poland",'phonecode' => 48,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 176,'shortname' => 'PT','name' => "Portugal",'phonecode' => 351,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 177,'shortname' => 'PR','name' => "Puerto Rico",'phonecode' => 1787,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 178,'shortname' => 'QA','name' => "Qatar",'phonecode' => 974,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 179,'shortname' => 'RE','name' => "Reunion",'phonecode' => 262,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 180,'shortname' => 'RO','name' => "Romania",'phonecode' => 40,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 181,'shortname' => 'RU','name' => "Russia",'phonecode' => 70,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 182,'shortname' => 'RW','name' => "Rwanda",'phonecode' => 250,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 183,'shortname' => 'SH','name' => "Saint Helena",'phonecode' => 290,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 184,'shortname' => 'KN','name' => "Saint Kitts And Nevis",'phonecode' => 1869,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 185,'shortname' => 'LC','name' => "Saint Lucia",'phonecode' => 1758,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 186,'shortname' => 'PM','name' => "Saint Pierre and Miquelon",'phonecode' => 508,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 187,'shortname' => 'VC','name' => "Saint Vincent And The Grenadines",'phonecode' => 1784,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 188,'shortname' => 'WS','name' => "Samoa",'phonecode' => 684,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 189,'shortname' => 'SM','name' => "San Marino",'phonecode' => 378,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 190,'shortname' => 'ST','name' => "Sao Tome and Principe",'phonecode' => 239,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 191,'shortname' => 'SA','name' => "Saudi Arabia",'phonecode' => 966,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 192,'shortname' => 'SN','name' => "Senegal",'phonecode' => 221,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 193,'shortname' => 'RS','name' => "Serbia",'phonecode' => 381,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 194,'shortname' => 'SC','name' => "Seychelles",'phonecode' => 248,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 195,'shortname' => 'SL','name' => "Sierra Leone",'phonecode' => 232,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 196,'shortname' => 'SG','name' => "Singapore",'phonecode' => 65,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 197,'shortname' => 'SK','name' => "Slovakia",'phonecode' => 421,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 198,'shortname' => 'SI','name' => "Slovenia",'phonecode' => 386,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 199,'shortname' => 'XG','name' => "Smaller Territories of the UK",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 200,'shortname' => 'SB','name' => "Solomon Islands",'phonecode' => 677,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 201,'shortname' => 'SO','name' => "Somalia",'phonecode' => 252,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 202,'shortname' => 'ZA','name' => "South Africa",'phonecode' => 27,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 203,'shortname' => 'GS','name' => "South Georgia",'phonecode' => 0,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 204,'shortname' => 'SS','name' => "South Sudan",'phonecode' => 211,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 205,'shortname' => 'ES','name' => "Spain",'phonecode' => 34,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 206,'shortname' => 'LK','name' => "Sri Lanka",'phonecode' => 94,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 207,'shortname' => 'SD','name' => "Sudan",'phonecode' => 249,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 208,'shortname' => 'SR','name' => "Suriname",'phonecode' => 597,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 209,'shortname' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phonecode' => 47,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 210,'shortname' => 'SZ','name' => "Swaziland",'phonecode' => 268,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 211,'shortname' => 'SE','name' => "Sweden",'phonecode' => 46,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 212,'shortname' => 'CH','name' => "Switzerland",'phonecode' => 41,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 213,'shortname' => 'SY','name' => "Syria",'phonecode' => 963,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 214,'shortname' => 'TW','name' => "Taiwan",'phonecode' => 886,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 215,'shortname' => 'TJ','name' => "Tajikistan",'phonecode' => 992,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 216,'shortname' => 'TZ','name' => "Tanzania",'phonecode' => 255,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 217,'shortname' => 'TH','name' => "Thailand",'phonecode' => 66,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 218,'shortname' => 'TG','name' => "Togo",'phonecode' => 228,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 219,'shortname' => 'TK','name' => "Tokelau",'phonecode' => 690,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 220,'shortname' => 'TO','name' => "Tonga",'phonecode' => 676,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 221,'shortname' => 'TT','name' => "Trinidad And Tobago",'phonecode' => 1868,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 222,'shortname' => 'TN','name' => "Tunisia",'phonecode' => 216,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 223,'shortname' => 'TR','name' => "Turkey",'phonecode' => 90,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 224,'shortname' => 'TM','name' => "Turkmenistan",'phonecode' => 7370,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 225,'shortname' => 'TC','name' => "Turks And Caicos Islands",'phonecode' => 1649,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 226,'shortname' => 'TV','name' => "Tuvalu",'phonecode' => 688,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 227,'shortname' => 'UG','name' => "Uganda",'phonecode' => 256,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 228,'shortname' => 'UA','name' => "Ukraine",'phonecode' => 380,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 229,'shortname' => 'AE','name' => "United Arab Emirates",'phonecode' => 971,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 230,'shortname' => 'GB','name' => "United Kingdom",'phonecode' => 44,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 231,'shortname' => 'US','name' => "United States",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 232,'shortname' => 'UM','name' => "United States Minor Outlying Islands",'phonecode' => 1,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 233,'shortname' => 'UY','name' => "Uruguay",'phonecode' => 598,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 234,'shortname' => 'UZ','name' => "Uzbekistan",'phonecode' => 998,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 235,'shortname' => 'VU','name' => "Vanuatu",'phonecode' => 678,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 236,'shortname' => 'VA','name' => "Vatican City State (Holy See)",'phonecode' => 39,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 237,'shortname' => 'VE','name' => "Venezuela",'phonecode' => 58,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 238,'shortname' => 'VN','name' => "Vietnam",'phonecode' => 84,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 239,'shortname' => 'VG','name' => "Virgin Islands (British)",'phonecode' => 1284,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 240,'shortname' => 'VI','name' => "Virgin Islands (US)",'phonecode' => 1340,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 241,'shortname' => 'WF','name' => "Wallis And Futuna Islands",'phonecode' => 681,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 242,'shortname' => 'EH','name' => "Western Sahara",'phonecode' => 212,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 243,'shortname' => 'YE','name' => "Yemen",'phonecode' => 967,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 244,'shortname' => 'YU','name' => "Yugoslavia",'phonecode' => 38,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 245,'shortname' => 'ZM','name' => "Zambia",'phonecode' => 260,'created_at' => Carbon::now(),'updated_at' => null,),
			array('id' => 246,'shortname' => 'ZW','name' => "Zimbabwe",'phonecode' => 263,'created_at' => Carbon::now(),'updated_at' => null,),
			);
			Region::insert($countries);
	}
}