<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\CountryCode;

class countrycodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CountryCode::truncate();

        $CountryCode = array(
            array('id' => '1','sortname' => 'AF','name' => 'AFGHANISTAN','country_name' => 'Afghanistan','iso3' => 'AFG','numcode' => '4','phonecode' => '93'),
            array('id' => '2','sortname' => 'AL','name' => 'ALBANIA','country_name' => 'Albania','iso3' => 'ALB','numcode' => '8','phonecode' => '355'),
            array('id' => '3','sortname' => 'DZ','name' => 'ALGERIA','country_name' => 'Algeria','iso3' => 'DZA','numcode' => '12','phonecode' => '213'),
            array('id' => '4','sortname' => 'AS','name' => 'AMERICAN SAMOA','country_name' => 'American Samoa','iso3' => 'ASM','numcode' => '16','phonecode' => '1684'),
            array('id' => '5','sortname' => 'AD','name' => 'ANDORRA','country_name' => 'Andorra','iso3' => 'AND','numcode' => '20','phonecode' => '376'),
            array('id' => '6','sortname' => 'AO','name' => 'ANGOLA','country_name' => 'Angola','iso3' => 'AGO','numcode' => '24','phonecode' => '244'),
            array('id' => '7','sortname' => 'AI','name' => 'ANGUILLA','country_name' => 'Anguilla','iso3' => 'AIA','numcode' => '660','phonecode' => '1264'),
            array('id' => '8','sortname' => 'AQ','name' => 'ANTARCTICA','country_name' => 'Antarctica','iso3' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '9','sortname' => 'AG','name' => 'ANTIGUA AND BARBUDA','country_name' => 'Antigua and Barbuda','iso3' => 'ATG','numcode' => '28','phonecode' => '1268'),
            array('id' => '10','sortname' => 'AR','name' => 'ARGENTINA','country_name' => 'Argentina','iso3' => 'ARG','numcode' => '32','phonecode' => '54'),
            array('id' => '11','sortname' => 'AM','name' => 'ARMENIA','country_name' => 'Armenia','iso3' => 'ARM','numcode' => '51','phonecode' => '374'),
            array('id' => '12','sortname' => 'AW','name' => 'ARUBA','country_name' => 'Aruba','iso3' => 'ABW','numcode' => '533','phonecode' => '297'),
            array('id' => '13','sortname' => 'AU','name' => 'AUSTRALIA','country_name' => 'Australia','iso3' => 'AUS','numcode' => '36','phonecode' => '61'),
            array('id' => '14','sortname' => 'AT','name' => 'AUSTRIA','country_name' => 'Austria','iso3' => 'AUT','numcode' => '40','phonecode' => '43'),
            array('id' => '15','sortname' => 'AZ','name' => 'AZERBAIJAN','country_name' => 'Azerbaijan','iso3' => 'AZE','numcode' => '31','phonecode' => '994'),
            array('id' => '16','sortname' => 'BS','name' => 'BAHAMAS','country_name' => 'Bahamas','iso3' => 'BHS','numcode' => '44','phonecode' => '1242'),
            array('id' => '17','sortname' => 'BH','name' => 'BAHRAIN','country_name' => 'Bahrain','iso3' => 'BHR','numcode' => '48','phonecode' => '973'),
            array('id' => '18','sortname' => 'BD','name' => 'BANGLADESH','country_name' => 'Bangladesh','iso3' => 'BGD','numcode' => '50','phonecode' => '880'),
            array('id' => '19','sortname' => 'BB','name' => 'BARBADOS','country_name' => 'Barbados','iso3' => 'BRB','numcode' => '52','phonecode' => '1246'),
            array('id' => '20','sortname' => 'BY','name' => 'BELARUS','country_name' => 'Belarus','iso3' => 'BLR','numcode' => '112','phonecode' => '375'),
            array('id' => '21','sortname' => 'BE','name' => 'BELGIUM','country_name' => 'Belgium','iso3' => 'BEL','numcode' => '56','phonecode' => '32'),
            array('id' => '22','sortname' => 'BZ','name' => 'BELIZE','country_name' => 'Belize','iso3' => 'BLZ','numcode' => '84','phonecode' => '501'),
            array('id' => '23','sortname' => 'BJ','name' => 'BENIN','country_name' => 'Benin','iso3' => 'BEN','numcode' => '204','phonecode' => '229'),
            array('id' => '24','sortname' => 'BM','name' => 'BERMUDA','country_name' => 'Bermuda','iso3' => 'BMU','numcode' => '60','phonecode' => '1441'),
            array('id' => '25','sortname' => 'BT','name' => 'BHUTAN','country_name' => 'Bhutan','iso3' => 'BTN','numcode' => '64','phonecode' => '975'),
            array('id' => '26','sortname' => 'BO','name' => 'BOLIVIA','country_name' => 'Bolivia','iso3' => 'BOL','numcode' => '68','phonecode' => '591'),
            array('id' => '27','sortname' => 'BA','name' => 'BOSNIA AND HERZEGOVINA','country_name' => 'Bosnia and Herzegovina','iso3' => 'BIH','numcode' => '70','phonecode' => '387'),
            array('id' => '28','sortname' => 'BW','name' => 'BOTSWANA','country_name' => 'Botswana','iso3' => 'BWA','numcode' => '72','phonecode' => '267'),
            array('id' => '29','sortname' => 'BV','name' => 'BOUVET ISLAND','country_name' => 'Bouvet Island','iso3' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '30','sortname' => 'BR','name' => 'BRAZIL','country_name' => 'Brazil','iso3' => 'BRA','numcode' => '76','phonecode' => '55'),
            array('id' => '31','sortname' => 'IO','name' => 'BRITISH INDIAN OCEAN TERRITORY','country_name' => 'British Indian Ocean Territory','iso3' => NULL,'numcode' => NULL,'phonecode' => '246'),
            array('id' => '32','sortname' => 'BN','name' => 'BRUNEI DARUSSALAM','country_name' => 'Brunei Darussalam','iso3' => 'BRN','numcode' => '96','phonecode' => '673'),
            array('id' => '33','sortname' => 'BG','name' => 'BULGARIA','country_name' => 'Bulgaria','iso3' => 'BGR','numcode' => '100','phonecode' => '359'),
            array('id' => '34','sortname' => 'BF','name' => 'BURKINA FASO','country_name' => 'Burkina Faso','iso3' => 'BFA','numcode' => '854','phonecode' => '226'),
            array('id' => '35','sortname' => 'BI','name' => 'BURUNDI','country_name' => 'Burundi','iso3' => 'BDI','numcode' => '108','phonecode' => '257'),
            array('id' => '36','sortname' => 'KH','name' => 'CAMBODIA','country_name' => 'Cambodia','iso3' => 'KHM','numcode' => '116','phonecode' => '855'),
            array('id' => '37','sortname' => 'CM','name' => 'CAMEROON','country_name' => 'Cameroon','iso3' => 'CMR','numcode' => '120','phonecode' => '237'),
            array('id' => '38','sortname' => 'CA','name' => 'CANADA','country_name' => 'Canada','iso3' => 'CAN','numcode' => '124','phonecode' => '1'),
            array('id' => '39','sortname' => 'CV','name' => 'CAPE VERDE','country_name' => 'Cape Verde','iso3' => 'CPV','numcode' => '132','phonecode' => '238'),
            array('id' => '40','sortname' => 'KY','name' => 'CAYMAN ISLANDS','country_name' => 'Cayman Islands','iso3' => 'CYM','numcode' => '136','phonecode' => '1345'),
            array('id' => '41','sortname' => 'CF','name' => 'CENTRAL AFRICAN REPUBLIC','country_name' => 'Central African Republic','iso3' => 'CAF','numcode' => '140','phonecode' => '236'),
            array('id' => '42','sortname' => 'TD','name' => 'CHAD','country_name' => 'Chad','iso3' => 'TCD','numcode' => '148','phonecode' => '235'),
            array('id' => '43','sortname' => 'CL','name' => 'CHILE','country_name' => 'Chile','iso3' => 'CHL','numcode' => '152','phonecode' => '56'),
            array('id' => '44','sortname' => 'CN','name' => 'CHINA','country_name' => 'China','iso3' => 'CHN','numcode' => '156','phonecode' => '86'),
            array('id' => '45','sortname' => 'CX','name' => 'CHRISTMAS ISLAND','country_name' => 'Christmas Island','iso3' => NULL,'numcode' => NULL,'phonecode' => '61'),
            array('id' => '46','sortname' => 'CC','name' => 'COCOS (KEELING) ISLANDS','country_name' => 'Cocos (Keeling) Islands','iso3' => NULL,'numcode' => NULL,'phonecode' => '672'),
            array('id' => '47','sortname' => 'CO','name' => 'COLOMBIA','country_name' => 'Colombia','iso3' => 'COL','numcode' => '170','phonecode' => '57'),
            array('id' => '48','sortname' => 'KM','name' => 'COMOROS','country_name' => 'Comoros','iso3' => 'COM','numcode' => '174','phonecode' => '269'),
            array('id' => '49','sortname' => 'CG','name' => 'CONGO','country_name' => 'Congo','iso3' => 'COG','numcode' => '178','phonecode' => '242'),
            array('id' => '50','sortname' => 'CD','name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','country_name' => 'Congo, the Democratic Republic of the','iso3' => 'COD','numcode' => '180','phonecode' => '242'),
            array('id' => '51','sortname' => 'CK','name' => 'COOK ISLANDS','country_name' => 'Cook Islands','iso3' => 'COK','numcode' => '184','phonecode' => '682'),
            array('id' => '52','sortname' => 'CR','name' => 'COSTA RICA','country_name' => 'Costa Rica','iso3' => 'CRI','numcode' => '188','phonecode' => '506'),
            array('id' => '53','sortname' => 'CI','name' => 'COTE D\'IVOIRE','country_name' => 'Cote D\'Ivoire','iso3' => 'CIV','numcode' => '384','phonecode' => '225'),
            array('id' => '54','sortname' => 'HR','name' => 'CROATIA','country_name' => 'Croatia','iso3' => 'HRV','numcode' => '191','phonecode' => '385'),
            array('id' => '55','sortname' => 'CU','name' => 'CUBA','country_name' => 'Cuba','iso3' => 'CUB','numcode' => '192','phonecode' => '53'),
            array('id' => '56','sortname' => 'CY','name' => 'CYPRUS','country_name' => 'Cyprus','iso3' => 'CYP','numcode' => '196','phonecode' => '357'),
            array('id' => '57','sortname' => 'CZ','name' => 'CZECH REPUBLIC','country_name' => 'Czech Republic','iso3' => 'CZE','numcode' => '203','phonecode' => '420'),
            array('id' => '58','sortname' => 'DK','name' => 'DENMARK','country_name' => 'Denmark','iso3' => 'DNK','numcode' => '208','phonecode' => '45'),
            array('id' => '59','sortname' => 'DJ','name' => 'DJIBOUTI','country_name' => 'Djibouti','iso3' => 'DJI','numcode' => '262','phonecode' => '253'),
            array('id' => '60','sortname' => 'DM','name' => 'DOMINICA','country_name' => 'Dominica','iso3' => 'DMA','numcode' => '212','phonecode' => '1767'),
            array('id' => '61','sortname' => 'DO','name' => 'DOMINICAN REPUBLIC','country_name' => 'Dominican Republic','iso3' => 'DOM','numcode' => '214','phonecode' => '1809'),
            array('id' => '62','sortname' => 'EC','name' => 'ECUADOR','country_name' => 'Ecuador','iso3' => 'ECU','numcode' => '218','phonecode' => '593'),
            array('id' => '63','sortname' => 'EG','name' => 'EGYPT','country_name' => 'Egypt','iso3' => 'EGY','numcode' => '818','phonecode' => '20'),
            array('id' => '64','sortname' => 'SV','name' => 'EL SALVADOR','country_name' => 'El Salvador','iso3' => 'SLV','numcode' => '222','phonecode' => '503'),
            array('id' => '65','sortname' => 'GQ','name' => 'EQUATORIAL GUINEA','country_name' => 'Equatorial Guinea','iso3' => 'GNQ','numcode' => '226','phonecode' => '240'),
            array('id' => '66','sortname' => 'ER','name' => 'ERITREA','country_name' => 'Eritrea','iso3' => 'ERI','numcode' => '232','phonecode' => '291'),
            array('id' => '67','sortname' => 'EE','name' => 'ESTONIA','country_name' => 'Estonia','iso3' => 'EST','numcode' => '233','phonecode' => '372'),
            array('id' => '68','sortname' => 'ET','name' => 'ETHIOPIA','country_name' => 'Ethiopia','iso3' => 'ETH','numcode' => '231','phonecode' => '251'),
            array('id' => '69','sortname' => 'FK','name' => 'FALKLAND ISLANDS (MALVINAS)','country_name' => 'Falkland Islands (Malvinas)','iso3' => 'FLK','numcode' => '238','phonecode' => '500'),
            array('id' => '70','sortname' => 'FO','name' => 'FAROE ISLANDS','country_name' => 'Faroe Islands','iso3' => 'FRO','numcode' => '234','phonecode' => '298'),
            array('id' => '71','sortname' => 'FJ','name' => 'FIJI','country_name' => 'Fiji','iso3' => 'FJI','numcode' => '242','phonecode' => '679'),
            array('id' => '72','sortname' => 'FI','name' => 'FINLAND','country_name' => 'Finland','iso3' => 'FIN','numcode' => '246','phonecode' => '358'),
            array('id' => '73','sortname' => 'FR','name' => 'FRANCE','country_name' => 'France','iso3' => 'FRA','numcode' => '250','phonecode' => '33'),
            array('id' => '74','sortname' => 'GF','name' => 'FRENCH GUIANA','country_name' => 'French Guiana','iso3' => 'GUF','numcode' => '254','phonecode' => '594'),
            array('id' => '75','sortname' => 'PF','name' => 'FRENCH POLYNESIA','country_name' => 'French Polynesia','iso3' => 'PYF','numcode' => '258','phonecode' => '689'),
            array('id' => '76','sortname' => 'TF','name' => 'FRENCH SOUTHERN TERRITORIES','country_name' => 'French Southern Territories','iso3' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '77','sortname' => 'GA','name' => 'GABON','country_name' => 'Gabon','iso3' => 'GAB','numcode' => '266','phonecode' => '241'),
            array('id' => '78','sortname' => 'GM','name' => 'GAMBIA','country_name' => 'Gambia','iso3' => 'GMB','numcode' => '270','phonecode' => '220'),
            array('id' => '79','sortname' => 'GE','name' => 'GEORGIA','country_name' => 'Georgia','iso3' => 'GEO','numcode' => '268','phonecode' => '995'),
            array('id' => '80','sortname' => 'DE','name' => 'GERMANY','country_name' => 'Germany','iso3' => 'DEU','numcode' => '276','phonecode' => '49'),
            array('id' => '81','sortname' => 'GH','name' => 'GHANA','country_name' => 'Ghana','iso3' => 'GHA','numcode' => '288','phonecode' => '233'),
            array('id' => '82','sortname' => 'GI','name' => 'GIBRALTAR','country_name' => 'Gibraltar','iso3' => 'GIB','numcode' => '292','phonecode' => '350'),
            array('id' => '83','sortname' => 'GR','name' => 'GREECE','country_name' => 'Greece','iso3' => 'GRC','numcode' => '300','phonecode' => '30'),
            array('id' => '84','sortname' => 'GL','name' => 'GREENLAND','country_name' => 'Greenland','iso3' => 'GRL','numcode' => '304','phonecode' => '299'),
            array('id' => '85','sortname' => 'GD','name' => 'GRENADA','country_name' => 'Grenada','iso3' => 'GRD','numcode' => '308','phonecode' => '1473'),
            array('id' => '86','sortname' => 'GP','name' => 'GUADELOUPE','country_name' => 'Guadeloupe','iso3' => 'GLP','numcode' => '312','phonecode' => '590'),
            array('id' => '87','sortname' => 'GU','name' => 'GUAM','country_name' => 'Guam','iso3' => 'GUM','numcode' => '316','phonecode' => '1671'),
            array('id' => '88','sortname' => 'GT','name' => 'GUATEMALA','country_name' => 'Guatemala','iso3' => 'GTM','numcode' => '320','phonecode' => '502'),
            array('id' => '89','sortname' => 'GN','name' => 'GUINEA','country_name' => 'Guinea','iso3' => 'GIN','numcode' => '324','phonecode' => '224'),
            array('id' => '90','sortname' => 'GW','name' => 'GUINEA-BISSAU','country_name' => 'Guinea-Bissau','iso3' => 'GNB','numcode' => '624','phonecode' => '245'),
            array('id' => '91','sortname' => 'GY','name' => 'GUYANA','country_name' => 'Guyana','iso3' => 'GUY','numcode' => '328','phonecode' => '592'),
            array('id' => '92','sortname' => 'HT','name' => 'HAITI','country_name' => 'Haiti','iso3' => 'HTI','numcode' => '332','phonecode' => '509'),
            array('id' => '93','sortname' => 'HM','name' => 'HEARD ISLAND AND MCDONALD ISLANDS','country_name' => 'Heard Island and Mcdonald Islands','iso3' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '94','sortname' => 'VA','name' => 'HOLY SEE (VATICAN CITY STATE)','country_name' => 'Holy See (Vatican City State)','iso3' => 'VAT','numcode' => '336','phonecode' => '39'),
            array('id' => '95','sortname' => 'HN','name' => 'HONDURAS','country_name' => 'Honduras','iso3' => 'HND','numcode' => '340','phonecode' => '504'),
            array('id' => '96','sortname' => 'HK','name' => 'HONG KONG','country_name' => 'Hong Kong','iso3' => 'HKG','numcode' => '344','phonecode' => '852'),
            array('id' => '97','sortname' => 'HU','name' => 'HUNGARY','country_name' => 'Hungary','iso3' => 'HUN','numcode' => '348','phonecode' => '36'),
            array('id' => '98','sortname' => 'IS','name' => 'ICELAND','country_name' => 'Iceland','iso3' => 'ISL','numcode' => '352','phonecode' => '354'),
            array('id' => '99','sortname' => 'IN','name' => 'INDIA','country_name' => 'India','iso3' => 'IND','numcode' => '356','phonecode' => '91'),
            array('id' => '100','sortname' => 'ID','name' => 'INDONESIA','country_name' => 'Indonesia','iso3' => 'IDN','numcode' => '360','phonecode' => '62'),
            array('id' => '101','sortname' => 'IR','name' => 'IRAN, ISLAMIC REPUBLIC OF','country_name' => 'Iran, Islamic Republic of','iso3' => 'IRN','numcode' => '364','phonecode' => '98'),
            array('id' => '102','sortname' => 'IQ','name' => 'IRAQ','country_name' => 'Iraq','iso3' => 'IRQ','numcode' => '368','phonecode' => '964'),
            array('id' => '103','sortname' => 'IE','name' => 'IRELAND','country_name' => 'Ireland','iso3' => 'IRL','numcode' => '372','phonecode' => '353'),
            array('id' => '104','sortname' => 'IL','name' => 'ISRAEL','country_name' => 'Israel','iso3' => 'ISR','numcode' => '376','phonecode' => '972'),
            array('id' => '105','sortname' => 'IT','name' => 'ITALY','country_name' => 'Italy','iso3' => 'ITA','numcode' => '380','phonecode' => '39'),
            array('id' => '106','sortname' => 'JM','name' => 'JAMAICA','country_name' => 'Jamaica','iso3' => 'JAM','numcode' => '388','phonecode' => '1876'),
            array('id' => '107','sortname' => 'JP','name' => 'JAPAN','country_name' => 'Japan','iso3' => 'JPN','numcode' => '392','phonecode' => '81'),
            array('id' => '108','sortname' => 'JO','name' => 'JORDAN','country_name' => 'Jordan','iso3' => 'JOR','numcode' => '400','phonecode' => '962'),
            array('id' => '109','sortname' => 'KZ','name' => 'KAZAKHSTAN','country_name' => 'Kazakhstan','iso3' => 'KAZ','numcode' => '398','phonecode' => '7'),
            array('id' => '110','sortname' => 'KE','name' => 'KENYA','country_name' => 'Kenya','iso3' => 'KEN','numcode' => '404','phonecode' => '254'),
            array('id' => '111','sortname' => 'KI','name' => 'KIRIBATI','country_name' => 'Kiribati','iso3' => 'KIR','numcode' => '296','phonecode' => '686'),
            array('id' => '112','sortname' => 'KP','name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','country_name' => 'Korea, Democratic People\'s Republic of','iso3' => 'PRK','numcode' => '408','phonecode' => '850'),
            array('id' => '113','sortname' => 'KR','name' => 'KOREA, REPUBLIC OF','country_name' => 'Korea, Republic of','iso3' => 'KOR','numcode' => '410','phonecode' => '82'),
            array('id' => '114','sortname' => 'KW','name' => 'KUWAIT','country_name' => 'Kuwait','iso3' => 'KWT','numcode' => '414','phonecode' => '965'),
            array('id' => '115','sortname' => 'KG','name' => 'KYRGYZSTAN','country_name' => 'Kyrgyzstan','iso3' => 'KGZ','numcode' => '417','phonecode' => '996'),
            array('id' => '116','sortname' => 'LA','name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC','country_name' => 'Lao People\'s Democratic Republic','iso3' => 'LAO','numcode' => '418','phonecode' => '856'),
            array('id' => '117','sortname' => 'LV','name' => 'LATVIA','country_name' => 'Latvia','iso3' => 'LVA','numcode' => '428','phonecode' => '371'),
            array('id' => '118','sortname' => 'LB','name' => 'LEBANON','country_name' => 'Lebanon','iso3' => 'LBN','numcode' => '422','phonecode' => '961'),
            array('id' => '119','sortname' => 'LS','name' => 'LESOTHO','country_name' => 'Lesotho','iso3' => 'LSO','numcode' => '426','phonecode' => '266'),
            array('id' => '120','sortname' => 'LR','name' => 'LIBERIA','country_name' => 'Liberia','iso3' => 'LBR','numcode' => '430','phonecode' => '231'),
            array('id' => '121','sortname' => 'LY','name' => 'LIBYAN ARAB JAMAHIRIYA','country_name' => 'Libyan Arab Jamahiriya','iso3' => 'LBY','numcode' => '434','phonecode' => '218'),
            array('id' => '122','sortname' => 'LI','name' => 'LIECHTENSTEIN','country_name' => 'Liechtenstein','iso3' => 'LIE','numcode' => '438','phonecode' => '423'),
            array('id' => '123','sortname' => 'LT','name' => 'LITHUANIA','country_name' => 'Lithuania','iso3' => 'LTU','numcode' => '440','phonecode' => '370'),
            array('id' => '124','sortname' => 'LU','name' => 'LUXEMBOURG','country_name' => 'Luxembourg','iso3' => 'LUX','numcode' => '442','phonecode' => '352'),
            array('id' => '125','sortname' => 'MO','name' => 'MACAO','country_name' => 'Macao','iso3' => 'MAC','numcode' => '446','phonecode' => '853'),
            array('id' => '126','sortname' => 'MK','name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','country_name' => 'Macedonia, the Former Yugoslav Republic of','iso3' => 'MKD','numcode' => '807','phonecode' => '389'),
            array('id' => '127','sortname' => 'MG','name' => 'MADAGASCAR','country_name' => 'Madagascar','iso3' => 'MDG','numcode' => '450','phonecode' => '261'),
            array('id' => '128','sortname' => 'MW','name' => 'MALAWI','country_name' => 'Malawi','iso3' => 'MWI','numcode' => '454','phonecode' => '265'),
            array('id' => '129','sortname' => 'MY','name' => 'MALAYSIA','country_name' => 'Malaysia','iso3' => 'MYS','numcode' => '458','phonecode' => '60'),
            array('id' => '130','sortname' => 'MV','name' => 'MALDIVES','country_name' => 'Maldives','iso3' => 'MDV','numcode' => '462','phonecode' => '960'),
            array('id' => '131','sortname' => 'ML','name' => 'MALI','country_name' => 'Mali','iso3' => 'MLI','numcode' => '466','phonecode' => '223'),
            array('id' => '132','sortname' => 'MT','name' => 'MALTA','country_name' => 'Malta','iso3' => 'MLT','numcode' => '470','phonecode' => '356'),
            array('id' => '133','sortname' => 'MH','name' => 'MARSHALL ISLANDS','country_name' => 'Marshall Islands','iso3' => 'MHL','numcode' => '584','phonecode' => '692'),
            array('id' => '134','sortname' => 'MQ','name' => 'MARTINIQUE','country_name' => 'Martinique','iso3' => 'MTQ','numcode' => '474','phonecode' => '596'),
            array('id' => '135','sortname' => 'MR','name' => 'MAURITANIA','country_name' => 'Mauritania','iso3' => 'MRT','numcode' => '478','phonecode' => '222'),
            array('id' => '136','sortname' => 'MU','name' => 'MAURITIUS','country_name' => 'Mauritius','iso3' => 'MUS','numcode' => '480','phonecode' => '230'),
            array('id' => '137','sortname' => 'YT','name' => 'MAYOTTE','country_name' => 'Mayotte','iso3' => NULL,'numcode' => NULL,'phonecode' => '269'),
            array('id' => '138','sortname' => 'MX','name' => 'MEXICO','country_name' => 'Mexico','iso3' => 'MEX','numcode' => '484','phonecode' => '52'),
            array('id' => '139','sortname' => 'FM','name' => 'MICRONESIA, FEDERATED STATES OF','country_name' => 'Micronesia, Federated States of','iso3' => 'FSM','numcode' => '583','phonecode' => '691'),
            array('id' => '140','sortname' => 'MD','name' => 'MOLDOVA, REPUBLIC OF','country_name' => 'Moldova, Republic of','iso3' => 'MDA','numcode' => '498','phonecode' => '373'),
            array('id' => '141','sortname' => 'MC','name' => 'MONACO','country_name' => 'Monaco','iso3' => 'MCO','numcode' => '492','phonecode' => '377'),
            array('id' => '142','sortname' => 'MN','name' => 'MONGOLIA','country_name' => 'Mongolia','iso3' => 'MNG','numcode' => '496','phonecode' => '976'),
            array('id' => '143','sortname' => 'MS','name' => 'MONTSERRAT','country_name' => 'Montserrat','iso3' => 'MSR','numcode' => '500','phonecode' => '1664'),
            array('id' => '144','sortname' => 'MA','name' => 'MOROCCO','country_name' => 'Morocco','iso3' => 'MAR','numcode' => '504','phonecode' => '212'),
            array('id' => '145','sortname' => 'MZ','name' => 'MOZAMBIQUE','country_name' => 'Mozambique','iso3' => 'MOZ','numcode' => '508','phonecode' => '258'),
            array('id' => '146','sortname' => 'MM','name' => 'MYANMAR','country_name' => 'Myanmar','iso3' => 'MMR','numcode' => '104','phonecode' => '95'),
            array('id' => '147','sortname' => 'NA','name' => 'NAMIBIA','country_name' => 'Namibia','iso3' => 'NAM','numcode' => '516','phonecode' => '264'),
            array('id' => '148','sortname' => 'NR','name' => 'NAURU','country_name' => 'Nauru','iso3' => 'NRU','numcode' => '520','phonecode' => '674'),
            array('id' => '149','sortname' => 'NP','name' => 'NEPAL','country_name' => 'Nepal','iso3' => 'NPL','numcode' => '524','phonecode' => '977'),
            array('id' => '150','sortname' => 'NL','name' => 'NETHERLANDS','country_name' => 'Netherlands','iso3' => 'NLD','numcode' => '528','phonecode' => '31'),
            array('id' => '151','sortname' => 'AN','name' => 'NETHERLANDS ANTILLES','country_name' => 'Netherlands Antilles','iso3' => 'ANT','numcode' => '530','phonecode' => '599'),
            array('id' => '152','sortname' => 'NC','name' => 'NEW CALEDONIA','country_name' => 'New Caledonia','iso3' => 'NCL','numcode' => '540','phonecode' => '687'),
            array('id' => '153','sortname' => 'NZ','name' => 'NEW ZEALAND','country_name' => 'New Zealand','iso3' => 'NZL','numcode' => '554','phonecode' => '64'),
            array('id' => '154','sortname' => 'NI','name' => 'NICARAGUA','country_name' => 'Nicaragua','iso3' => 'NIC','numcode' => '558','phonecode' => '505'),
            array('id' => '155','sortname' => 'NE','name' => 'NIGER','country_name' => 'Niger','iso3' => 'NER','numcode' => '562','phonecode' => '227'),
            array('id' => '156','sortname' => 'NG','name' => 'NIGERIA','country_name' => 'Nigeria','iso3' => 'NGA','numcode' => '566','phonecode' => '234'),
            array('id' => '157','sortname' => 'NU','name' => 'NIUE','country_name' => 'Niue','iso3' => 'NIU','numcode' => '570','phonecode' => '683'),
            array('id' => '158','sortname' => 'NF','name' => 'NORFOLK ISLAND','country_name' => 'Norfolk Island','iso3' => 'NFK','numcode' => '574','phonecode' => '672'),
            array('id' => '159','sortname' => 'MP','name' => 'NORTHERN MARIANA ISLANDS','country_name' => 'Northern Mariana Islands','iso3' => 'MNP','numcode' => '580','phonecode' => '1670'),
            array('id' => '160','sortname' => 'NO','name' => 'NORWAY','country_name' => 'Norway','iso3' => 'NOR','numcode' => '578','phonecode' => '47'),
            array('id' => '161','sortname' => 'OM','name' => 'OMAN','country_name' => 'Oman','iso3' => 'OMN','numcode' => '512','phonecode' => '968'),
            array('id' => '162','sortname' => 'PK','name' => 'PAKISTAN','country_name' => 'Pakistan','iso3' => 'PAK','numcode' => '586','phonecode' => '92'),
            array('id' => '163','sortname' => 'PW','name' => 'PALAU','country_name' => 'Palau','iso3' => 'PLW','numcode' => '585','phonecode' => '680'),
            array('id' => '164','sortname' => 'PS','name' => 'PALESTINIAN TERRITORY, OCCUPIED','country_name' => 'Palestinian Territory, Occupied','iso3' => NULL,'numcode' => NULL,'phonecode' => '970'),
            array('id' => '165','sortname' => 'PA','name' => 'PANAMA','country_name' => 'Panama','iso3' => 'PAN','numcode' => '591','phonecode' => '507'),
            array('id' => '166','sortname' => 'PG','name' => 'PAPUA NEW GUINEA','country_name' => 'Papua New Guinea','iso3' => 'PNG','numcode' => '598','phonecode' => '675'),
            array('id' => '167','sortname' => 'PY','name' => 'PARAGUAY','country_name' => 'Paraguay','iso3' => 'PRY','numcode' => '600','phonecode' => '595'),
            array('id' => '168','sortname' => 'PE','name' => 'PERU','country_name' => 'Peru','iso3' => 'PER','numcode' => '604','phonecode' => '51'),
            array('id' => '169','sortname' => 'PH','name' => 'PHILIPPINES','country_name' => 'Philippines','iso3' => 'PHL','numcode' => '608','phonecode' => '63'),
            array('id' => '170','sortname' => 'PN','name' => 'PITCAIRN','country_name' => 'Pitcairn','iso3' => 'PCN','numcode' => '612','phonecode' => '0'),
            array('id' => '171','sortname' => 'PL','name' => 'POLAND','country_name' => 'Poland','iso3' => 'POL','numcode' => '616','phonecode' => '48'),
            array('id' => '172','sortname' => 'PT','name' => 'PORTUGAL','country_name' => 'Portugal','iso3' => 'PRT','numcode' => '620','phonecode' => '351'),
            array('id' => '173','sortname' => 'PR','name' => 'PUERTO RICO','country_name' => 'Puerto Rico','iso3' => 'PRI','numcode' => '630','phonecode' => '1787'),
            array('id' => '174','sortname' => 'QA','name' => 'QATAR','country_name' => 'Qatar','iso3' => 'QAT','numcode' => '634','phonecode' => '974'),
            array('id' => '175','sortname' => 'RE','name' => 'REUNION','country_name' => 'Reunion','iso3' => 'REU','numcode' => '638','phonecode' => '262'),
            array('id' => '176','sortname' => 'RO','name' => 'ROMANIA','country_name' => 'Romania','iso3' => 'ROM','numcode' => '642','phonecode' => '40'),
            array('id' => '177','sortname' => 'RU','name' => 'RUSSIAN FEDERATION','country_name' => 'Russian Federation','iso3' => 'RUS','numcode' => '643','phonecode' => '70'),
            array('id' => '178','sortname' => 'RW','name' => 'RWANDA','country_name' => 'Rwanda','iso3' => 'RWA','numcode' => '646','phonecode' => '250'),
            array('id' => '179','sortname' => 'SH','name' => 'SAINT HELENA','country_name' => 'Saint Helena','iso3' => 'SHN','numcode' => '654','phonecode' => '290'),
            array('id' => '180','sortname' => 'KN','name' => 'SAINT KITTS AND NEVIS','country_name' => 'Saint Kitts and Nevis','iso3' => 'KNA','numcode' => '659','phonecode' => '1869'),
            array('id' => '181','sortname' => 'LC','name' => 'SAINT LUCIA','country_name' => 'Saint Lucia','iso3' => 'LCA','numcode' => '662','phonecode' => '1758'),
            array('id' => '182','sortname' => 'PM','name' => 'SAINT PIERRE AND MIQUELON','country_name' => 'Saint Pierre and Miquelon','iso3' => 'SPM','numcode' => '666','phonecode' => '508'),
            array('id' => '183','sortname' => 'VC','name' => 'SAINT VINCENT AND THE GRENADINES','country_name' => 'Saint Vincent and the Grenadines','iso3' => 'VCT','numcode' => '670','phonecode' => '1784'),
            array('id' => '184','sortname' => 'WS','name' => 'SAMOA','country_name' => 'Samoa','iso3' => 'WSM','numcode' => '882','phonecode' => '684'),
            array('id' => '185','sortname' => 'SM','name' => 'SAN MARINO','country_name' => 'San Marino','iso3' => 'SMR','numcode' => '674','phonecode' => '378'),
            array('id' => '186','sortname' => 'ST','name' => 'SAO TOME AND PRINCIPE','country_name' => 'Sao Tome and Principe','iso3' => 'STP','numcode' => '678','phonecode' => '239'),
            array('id' => '187','sortname' => 'SA','name' => 'SAUDI ARABIA','country_name' => 'Saudi Arabia','iso3' => 'SAU','numcode' => '682','phonecode' => '966'),
            array('id' => '188','sortname' => 'SN','name' => 'SENEGAL','country_name' => 'Senegal','iso3' => 'SEN','numcode' => '686','phonecode' => '221'),
            array('id' => '189','sortname' => 'CS','name' => 'SERBIA AND MONTENEGRO','country_name' => 'Serbia and Montenegro','iso3' => NULL,'numcode' => NULL,'phonecode' => '381'),
            array('id' => '190','sortname' => 'SC','name' => 'SEYCHELLES','country_name' => 'Seychelles','iso3' => 'SYC','numcode' => '690','phonecode' => '248'),
            array('id' => '191','sortname' => 'SL','name' => 'SIERRA LEONE','country_name' => 'Sierra Leone','iso3' => 'SLE','numcode' => '694','phonecode' => '232'),
            array('id' => '192','sortname' => 'SG','name' => 'SINGAPORE','country_name' => 'Singapore','iso3' => 'SGP','numcode' => '702','phonecode' => '65'),
            array('id' => '193','sortname' => 'SK','name' => 'SLOVAKIA','country_name' => 'Slovakia','iso3' => 'SVK','numcode' => '703','phonecode' => '421'),
            array('id' => '194','sortname' => 'SI','name' => 'SLOVENIA','country_name' => 'Slovenia','iso3' => 'SVN','numcode' => '705','phonecode' => '386'),
            array('id' => '195','sortname' => 'SB','name' => 'SOLOMON ISLANDS','country_name' => 'Solomon Islands','iso3' => 'SLB','numcode' => '90','phonecode' => '677'),
            array('id' => '196','sortname' => 'SO','name' => 'SOMALIA','country_name' => 'Somalia','iso3' => 'SOM','numcode' => '706','phonecode' => '252'),
            array('id' => '197','sortname' => 'ZA','name' => 'SOUTH AFRICA','country_name' => 'South Africa','iso3' => 'ZAF','numcode' => '710','phonecode' => '27'),
            array('id' => '198','sortname' => 'GS','name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','country_name' => 'South Georgia and the South Sandwich Islands','iso3' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '199','sortname' => 'ES','name' => 'SPAIN','country_name' => 'Spain','iso3' => 'ESP','numcode' => '724','phonecode' => '34'),
            array('id' => '200','sortname' => 'LK','name' => 'SRI LANKA','country_name' => 'Sri Lanka','iso3' => 'LKA','numcode' => '144','phonecode' => '94'),
            array('id' => '201','sortname' => 'SD','name' => 'SUDAN','country_name' => 'Sudan','iso3' => 'SDN','numcode' => '736','phonecode' => '249'),
            array('id' => '202','sortname' => 'SR','name' => 'SURINAME','country_name' => 'Suriname','iso3' => 'SUR','numcode' => '740','phonecode' => '597'),
            array('id' => '203','sortname' => 'SJ','name' => 'SVALBARD AND JAN MAYEN','country_name' => 'Svalbard and Jan Mayen','iso3' => 'SJM','numcode' => '744','phonecode' => '47'),
            array('id' => '204','sortname' => 'SZ','name' => 'SWAZILAND','country_name' => 'Swaziland','iso3' => 'SWZ','numcode' => '748','phonecode' => '268'),
            array('id' => '205','sortname' => 'SE','name' => 'SWEDEN','country_name' => 'Sweden','iso3' => 'SWE','numcode' => '752','phonecode' => '46'),
            array('id' => '206','sortname' => 'CH','name' => 'SWITZERLAND','country_name' => 'Switzerland','iso3' => 'CHE','numcode' => '756','phonecode' => '41'),
            array('id' => '207','sortname' => 'SY','name' => 'SYRIAN ARAB REPUBLIC','country_name' => 'Syrian Arab Republic','iso3' => 'SYR','numcode' => '760','phonecode' => '963'),
            array('id' => '208','sortname' => 'TW','name' => 'TAIWAN, PROVINCE OF CHINA','country_name' => 'Taiwan, Province of China','iso3' => 'TWN','numcode' => '158','phonecode' => '886'),
            array('id' => '209','sortname' => 'TJ','name' => 'TAJIKISTAN','country_name' => 'Tajikistan','iso3' => 'TJK','numcode' => '762','phonecode' => '992'),
            array('id' => '210','sortname' => 'TZ','name' => 'TANZANIA, UNITED REPUBLIC OF','country_name' => 'Tanzania, United Republic of','iso3' => 'TZA','numcode' => '834','phonecode' => '255'),
            array('id' => '211','sortname' => 'TH','name' => 'THAILAND','country_name' => 'Thailand','iso3' => 'THA','numcode' => '764','phonecode' => '66'),
            array('id' => '212','sortname' => 'TL','name' => 'TIMOR-LESTE','country_name' => 'Timor-Leste','iso3' => NULL,'numcode' => NULL,'phonecode' => '670'),
            array('id' => '213','sortname' => 'TG','name' => 'TOGO','country_name' => 'Togo','iso3' => 'TGO','numcode' => '768','phonecode' => '228'),
            array('id' => '214','sortname' => 'TK','name' => 'TOKELAU','country_name' => 'Tokelau','iso3' => 'TKL','numcode' => '772','phonecode' => '690'),
            array('id' => '215','sortname' => 'TO','name' => 'TONGA','country_name' => 'Tonga','iso3' => 'TON','numcode' => '776','phonecode' => '676'),
            array('id' => '216','sortname' => 'TT','name' => 'TRINIDAD AND TOBAGO','country_name' => 'Trinidad and Tobago','iso3' => 'TTO','numcode' => '780','phonecode' => '1868'),
            array('id' => '217','sortname' => 'TN','name' => 'TUNISIA','country_name' => 'Tunisia','iso3' => 'TUN','numcode' => '788','phonecode' => '216'),
            array('id' => '218','sortname' => 'TR','name' => 'TURKEY','country_name' => 'Turkey','iso3' => 'TUR','numcode' => '792','phonecode' => '90'),
            array('id' => '219','sortname' => 'TM','name' => 'TURKMENISTAN','country_name' => 'Turkmenistan','iso3' => 'TKM','numcode' => '795','phonecode' => '7370'),
            array('id' => '220','sortname' => 'TC','name' => 'TURKS AND CAICOS ISLANDS','country_name' => 'Turks and Caicos Islands','iso3' => 'TCA','numcode' => '796','phonecode' => '1649'),
            array('id' => '221','sortname' => 'TV','name' => 'TUVALU','country_name' => 'Tuvalu','iso3' => 'TUV','numcode' => '798','phonecode' => '688'),
            array('id' => '222','sortname' => 'UG','name' => 'UGANDA','country_name' => 'Uganda','iso3' => 'UGA','numcode' => '800','phonecode' => '256'),
            array('id' => '223','sortname' => 'UA','name' => 'UKRAINE','country_name' => 'Ukraine','iso3' => 'UKR','numcode' => '804','phonecode' => '380'),
            array('id' => '224','sortname' => 'AE','name' => 'UNITED ARAB EMIRATES','country_name' => 'United Arab Emirates','iso3' => 'ARE','numcode' => '784','phonecode' => '971'),
            array('id' => '225','sortname' => 'GB','name' => 'UNITED KINGDOM','country_name' => 'United Kingdom','iso3' => 'GBR','numcode' => '826','phonecode' => '44'),
            array('id' => '226','sortname' => 'US','name' => 'UNITED STATES','country_name' => 'United States','iso3' => 'USA','numcode' => '840','phonecode' => '1'),
            array('id' => '227','sortname' => 'UM','name' => 'UNITED STATES MINOR OUTLYING ISLANDS','country_name' => 'United States Minor Outlying Islands','iso3' => NULL,'numcode' => NULL,'phonecode' => '1'),
            array('id' => '228','sortname' => 'UY','name' => 'URUGUAY','country_name' => 'Uruguay','iso3' => 'URY','numcode' => '858','phonecode' => '598'),
            array('id' => '229','sortname' => 'UZ','name' => 'UZBEKISTAN','country_name' => 'Uzbekistan','iso3' => 'UZB','numcode' => '860','phonecode' => '998'),
            array('id' => '230','sortname' => 'VU','name' => 'VANUATU','country_name' => 'Vanuatu','iso3' => 'VUT','numcode' => '548','phonecode' => '678'),
            array('id' => '231','sortname' => 'VE','name' => 'VENEZUELA','country_name' => 'Venezuela','iso3' => 'VEN','numcode' => '862','phonecode' => '58'),
            array('id' => '232','sortname' => 'VN','name' => 'VIET NAM','country_name' => 'Viet Nam','iso3' => 'VNM','numcode' => '704','phonecode' => '84'),
            array('id' => '233','sortname' => 'VG','name' => 'VIRGIN ISLANDS, BRITISH','country_name' => 'Virgin Islands, British','iso3' => 'VGB','numcode' => '92','phonecode' => '1284'),
            array('id' => '234','sortname' => 'VI','name' => 'VIRGIN ISLANDS, U.S.','country_name' => 'Virgin Islands, U.s.','iso3' => 'VIR','numcode' => '850','phonecode' => '1340'),
            array('id' => '235','sortname' => 'WF','name' => 'WALLIS AND FUTUNA','country_name' => 'Wallis and Futuna','iso3' => 'WLF','numcode' => '876','phonecode' => '681'),
            array('id' => '236','sortname' => 'EH','name' => 'WESTERN SAHARA','country_name' => 'Western Sahara','iso3' => 'ESH','numcode' => '732','phonecode' => '212'),
            array('id' => '237','sortname' => 'YE','name' => 'YEMEN','country_name' => 'Yemen','iso3' => 'YEM','numcode' => '887','phonecode' => '967'),
            array('id' => '238','sortname' => 'ZM','name' => 'ZAMBIA','country_name' => 'Zambia','iso3' => 'ZMB','numcode' => '894','phonecode' => '260'),
            array('id' => '239','sortname' => 'ZW','name' => 'ZIMBABWE','country_name' => 'Zimbabwe','iso3' => 'ZWE','numcode' => '716','phonecode' => '263'),
            array('id' => '240','sortname' => 'RS','name' => 'SERBIA','country_name' => 'Serbia','iso3' => 'SRB','numcode' => '688','phonecode' => '381'),
            array('id' => '241','sortname' => 'AP','name' => 'ASIA PACIFIC REGION','country_name' => 'Asia / Pacific Region','iso3' => '0','numcode' => '0','phonecode' => '0'),
            array('id' => '242','sortname' => 'ME','name' => 'MONTENEGRO','country_name' => 'Montenegro','iso3' => 'MNE','numcode' => '499','phonecode' => '382'),
            array('id' => '243','sortname' => 'AX','name' => 'ALAND ISLANDS','country_name' => 'Aland Islands','iso3' => 'ALA','numcode' => '248','phonecode' => '358'),
            array('id' => '244','sortname' => 'BQ','name' => 'BONAIRE, SINT EUSTATIUS AND SABA','country_name' => 'Bonaire, Sint Eustatius and Saba','iso3' => 'BES','numcode' => '535','phonecode' => '599'),
            array('id' => '245','sortname' => 'CW','name' => 'CURACAO','country_name' => 'Curacao','iso3' => 'CUW','numcode' => '531','phonecode' => '599'),
            array('id' => '246','sortname' => 'GG','name' => 'GUERNSEY','country_name' => 'Guernsey','iso3' => 'GGY','numcode' => '831','phonecode' => '44'),
            array('id' => '247','sortname' => 'IM','name' => 'ISLE OF MAN','country_name' => 'Isle of Man','iso3' => 'IMN','numcode' => '833','phonecode' => '44'),
            array('id' => '248','sortname' => 'JE','name' => 'JERSEY','country_name' => 'Jersey','iso3' => 'JEY','numcode' => '832','phonecode' => '44'),
            array('id' => '249','sortname' => 'XK','name' => 'KOSOVO','country_name' => 'Kosovo','iso3' => '---','numcode' => '0','phonecode' => '381'),
            array('id' => '250','sortname' => 'BL','name' => 'SAINT BARTHELEMY','country_name' => 'Saint Barthelemy','iso3' => 'BLM','numcode' => '652','phonecode' => '590'),
            array('id' => '251','sortname' => 'MF','name' => 'SAINT MARTIN','country_name' => 'Saint Martin','iso3' => 'MAF','numcode' => '663','phonecode' => '590'),
            array('id' => '252','sortname' => 'SX','name' => 'SINT MAARTEN','country_name' => 'Sint Maarten','iso3' => 'SXM','numcode' => '534','phonecode' => '1'),
            array('id' => '253','sortname' => 'SS','name' => 'SOUTH SUDAN','country_name' => 'South Sudan','iso3' => 'SSD','numcode' => '728','phonecode' => '211')
          );


        CountryCode::insert($CountryCode);
    }
}
