<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Currency;

class CurrenciesTableseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

    Currency::truncate();
    

    $Currency = array(
        array('id' =>1,'country' =>  "Albania",'currencies' =>  "Leke",'code' =>  "ALL", 'symbol' => "Lek"),
        array('id' =>2,'country' =>  "America", 'currencies' => "Dollars",'code' =>  "USD",'symbol' =>  "$"),
        array('id' =>3,'country' =>  "Afghanistan",'currencies' =>  "Afghanis",'code' =>  "AFN",'symbol' =>  "؋"),
        array('id' =>4,'country' =>  "Argentina", 'currencies' => "Pesos", 'code' => "ARS", 'symbol' => "$"),
        array('id' =>5, 'country' => "Aruba",'currencies' =>  "Guilders",'code' =>  "AWG",'symbol' =>  "ƒ"),
        array('id' =>6, 'country' => "Australia", 'currencies' => "Dollars",'code' =>  "AUD",'symbol' =>  "$"),
        array('id' =>7, 'country' => "Azerbaijan",'currencies' =>  "New Manats",'code' =>  "AZN",'symbol' =>  "ман"),
        array('id' =>8, 'country' => "Bahamas", 'currencies' => "Dollars", 'code' => "BSD",'symbol' =>  "$"),
        array('id' =>9, 'country' => "Barbados",'currencies' =>  "Dollars",'code' =>  "BBD", 'symbol' => "$"),
        array('id' =>10, 'country' => "Belarus",'currencies' =>  "Rubles",'code' =>  "BYR",'symbol' =>  "p."),
        array('id' =>11, 'country' => "Belgium",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>12, 'country' => "Beliz", 'currencies' => "Dollars",'code' =>  "BZD",'symbol' =>  "BZ$"),
        array('id' =>13, 'country' => "Bermuda",'currencies' =>  "Dollars",'code' =>  "BMD",'symbol' =>  "$"),
        array('id' =>14, 'country' => "Bolivia", 'currencies' => "Bolivianos",'code' =>  "BOB",'symbol' =>  '$b'),
        array('id' =>15, 'country' => "Bosnia and Herzegovina",'currencies' =>  "Convertible Marka",'code' =>  "BAM",'symbol' =>  "KM"),
        array('id' =>16, 'country' => "Botswana", 'currencies' => "Pula",'code' =>  "BWP",'symbol' =>  "P"),
        array('id' =>17, 'country' => "Bulgaria", 'currencies' => "Leva",'code' =>  "BGN",'symbol' =>  "лв"),
        array('id' =>18, 'country' => "Brazil", 'currencies' => "Reais",'code' =>  "BRL",'symbol' =>  "R$"),
        array('id' =>19, 'country' => "Britain (United Kingdom)", 'currencies' => "Pounds",'code' =>  "GBP",'symbol' =>  "£"),
        array('id' =>20, 'country' => "Brunei Darussalam",'currencies' =>  "Dollars",'code' =>  "BND",'symbol' =>  "$"),
        array('id' =>21, 'country' => "Cambodia", 'currencies' => "Riels",'code' =>  "KHR",'symbol' =>  "៛"),
        array('id' =>22, 'country' => "Canada", 'currencies' => "Dollars",'code' =>  "CAD",'symbol' =>  "$"),
        array('id' =>23, 'country' => "Cayman Islands",'currencies' =>  "Dollars",'code' =>  "KYD",'symbol' =>  "$"),
        array('id' =>24, 'country' => "Chile",'currencies' =>  "Pesos",'code' =>  "CLP",'symbol' =>  "$"),
        array('id' =>25, 'country' => "China",'currencies' =>  "Yuan Renminbi",'code' =>  "CNY",'symbol' =>  "¥"),
        array('id' =>26, 'country' => "Colombia",'currencies' =>  "Pesos",'code' =>  "COP",'symbol' =>  "$"),
        array('id' =>27, 'country' => "Costa Rica",'currencies' =>  "Colón",'code' =>  "CRC",'symbol' =>  "₡"),
        array('id' =>28, 'country' => "Croatia", 'currencies' => "Kuna",'code' =>  "HRK",'symbol' =>  "kn"),
        array('id' =>29, 'country' => "Cuba", 'currencies' => "Pesos",'code' =>  "CUP",'symbol' =>  "₱"),
        array('id' =>30, 'country' => "Cyprus",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>31, 'country' => "Czech Republic",'currencies' =>  "Koruny",'code' =>  "CZK",'symbol' =>  "Kč"),
        array('id' =>32, 'country' => "Denmark", 'currencies' => "Kroner",'code' =>  "DKK",'symbol' =>  "kr"),
        array('id' =>33, 'country' => "Dominican Republic",'currencies' =>  "Pesos",'code' =>  "DOP ",'symbol' =>  "RD$"),
        array('id' =>34, 'country' => "East Caribbean", 'currencies' => "Dollars",'code' =>  "XCD",'symbol' =>  "$"),
        array('id' =>35, 'country' => "Egypt", 'currencies' => "Pounds",'code' =>  "EGP",'symbol' =>  "£"),
        array('id' =>36, 'country' => "El Salvador", 'currencies' => "Colones",'code' =>  "SVC",'symbol' =>  "$"),
        array('id' =>37, 'country' => "England array('id' =>United Kingdom)",'currencies' =>  "Pounds",'code' =>  "GBP",'symbol' =>  "£"),
        array('id' =>38, 'country' => "Euro", 'currencies' => "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>39, 'country' => "Falkland Islands",'currencies' =>  "Pounds",'code' =>  "FKP",'symbol' =>  "£"),
        array('id' =>40, 'country' => "Fiji",'currencies' =>  "Dollars",'code' =>  "FJD",'symbol' =>  "$"),
        array('id' =>41, 'country' => "France",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>42, 'country' => "Ghana",'currencies' =>  "Cedis",'code' =>  "GHC",'symbol' =>  "¢"),
        array('id' =>43, 'country' => "Gibraltar",'currencies' =>  "Pounds",'code' =>  "GIP",'symbol' =>  "£"),
        array('id' =>44, 'country' => "Greece",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>45, 'country' => "Guatemala",'currencies' =>  "Quetzales",'code' =>  "GTQ",'symbol' =>  "Q"),
        array('id' =>46, 'country' => "Guernsey", 'currencies' => "Pounds",'code' =>  "GGP",'symbol' =>  "£"),
        array('id' =>47, 'country' => "Guyana", 'currencies' => "Dollars",'code' =>  "GYD",'symbol' =>  "$"),
        array('id' =>48, 'country' => "Holland array('id' =>Netherlands)",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>49, 'country' => "Honduras",'currencies' =>  "Lempiras",'code' =>  "HNL",'symbol' =>  "L"),
        array('id' =>50, 'country' => "Hong Kong",'currencies' =>  "Dollars",'code' =>  "HKD",'symbol' =>  "$"),
        array('id' =>51, 'country' => "Hungary",'currencies' =>  "Forint",'code' =>  "HUF",'symbol' =>  "Ft"),
        array('id' =>52, 'country' => "Iceland",'currencies' =>  "Kronur",'code' =>  "ISK",'symbol' =>  "kr"),
        array('id' =>53, 'country' => "India",'currencies' =>  "Rupees",'code' =>  "INR",'symbol' =>  "₹"),
        array('id' =>54, 'country' => "Indonesia",'currencies' =>  "Rupiahs",'code' =>  "IDR",'symbol' =>  "Rp"),
        array('id' =>55, 'country' => "Iran",'currencies' =>  "Rials",'code' =>  "IRR",'symbol' =>  "﷼"),
        array('id' =>56, 'country' => "Ireland",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>57, 'country' => "Isle of Man",'currencies' =>  "Pounds",'code' =>  "IMP",'symbol' =>  "£"),
        array('id' =>58, 'country' => "Israel",'currencies' =>  "New Shekels",'code' =>  "ILS", 'symbol' => "₪"),
        array('id' =>59, 'country' => "Italy",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>60, 'country' => "Jamaica",'currencies' =>  "Dollars",'code' =>  "JMD",'symbol' =>  "J$"),
        array('id' =>61, 'country' => "Japan",'currencies' =>  "Yen",'code' =>  "JPY",'symbol' =>  "¥"),
        array('id' =>62, 'country' => "Jersey",'currencies' =>  "Pounds",'code' =>  "JEP",'symbol' =>  "£"),
        array('id' =>63, 'country' => "Kazakhstan",'currencies' =>  "Tenge",'code' =>  "KZT",'symbol' =>  "лв"),
        array('id' =>64, 'country' => "Korea array('id' =>North)",'currencies' =>  "Won",'code' =>  "KPW",'symbol' =>  "₩"),
        array('id' =>65, 'country' => "Korea array('id' =>South)",'currencies' =>  "Won",'code' =>  "KRW",'symbol' =>  "₩"),
        array('id' =>66, 'country' => "Kyrgyzstan",'currencies' =>  "Soms",'code' =>  "KGS",'symbol' =>  "лв"),
        array('id' =>67, 'country' => "Laos",'currencies' =>  "Kips",'code' =>  "LAK",'symbol' =>  "₭"),
        array('id' =>68, 'country' => "Latvia",'currencies' =>  "Lati",'code' =>  "LVL",'symbol' =>  "Ls"),
        array('id' =>69, 'country' => "Lebanon",'currencies' =>  "Pounds",'code' =>  "LBP",'symbol' =>  "£"),
        array('id' =>70, 'country' => "Liberia",'currencies' =>  "Dollars",'code' =>  "LRD",'symbol' =>  "$"),
        array('id' =>71, 'country' => "Liechtenstein",'currencies' =>  "Switzerland Francs",'code' =>  "CHF",'symbol' =>  "CHF"),
        array('id' =>72, 'country' => "Lithuania",'currencies' =>  "Litai",'code' =>  "LTL",'symbol' =>  "Lt"),
        array('id' =>73, 'country' => "Luxembourg",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>74, 'country' => "Macedonia", 'currencies' => "Denars",'code' =>  "MKD", 'symbol' => "ден"),
        array('id' =>75, 'country' => "Malaysia", 'currencies' => "Ringgits",'code' =>  "MYR",'symbol' =>  "RM"),
        array('id' =>76, 'country' => "Malta", 'currencies' => "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>77, 'country' => "Mauritius",'currencies' =>  "Rupees",'code' =>  "MUR", 'symbol' => "₨"),
        array('id' =>78, 'country' => "Mexico",'currencies' =>  "Pesos",'code' =>  "MXN",'symbol' =>  "$"),
        array('id' =>79, 'country' => "Mongolia",'currencies' =>  "Tugriks",'code' =>  "MNT",'symbol' =>  "₮"),
        array('id' =>80, 'country' => "Mozambique",'currencies' =>  "Meticais",'code' =>  "MZN",'symbol' =>  "MT"),
        array('id' =>81, 'country' => "Namibia",'currencies' =>  "Dollars",'code' =>  "NAD",'symbol' =>  "$"),
        array('id' =>82, 'country' => "Nepal", 'currencies' => "Rupees",'code' =>  "NPR",'symbol' =>  "₨"),
        array('id' =>83, 'country' => "Netherlands Antilles",'currencies' =>  "Guilders",'code' =>  "ANG",'symbol' =>  "ƒ"),
        array('id' =>84, 'country' => "Netherlands",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>85, 'country' => "New Zealand",'currencies' =>  "Dollars",'code' =>  "NZD",'symbol' =>  "$"),
        array('id' =>86, 'country' => "Nicaragua", 'currencies' =>  "Cordobas",'code' =>  "NIO",'symbol' =>  "C$"),
        array('id' =>87, 'country' => "Nigeria",'currencies' =>  "Nairas",'code' =>  "NGN",'symbol' =>  "₦"),
        array('id' =>88, 'country' => "North Korea",'currencies' =>  "Won",'code' =>  "KPW",'symbol' =>  "₩"),
        array('id' =>89, 'country' => "Norway",'currencies' =>  "Krone",'code' =>  "NOK",'symbol' =>  "kr"),
        array('id' =>90, 'country' => "Oman",'currencies' =>  "Rials",'code' =>  "OMR",'symbol' =>  "﷼"),
        array('id' =>91, 'country' => "Pakistan",'currencies' =>  "Rupees",'code' =>  "PKR",'symbol' =>  "₨"),
        array('id' =>92, 'country' => "Panama",'currencies' =>  "Balboa",'code' =>  "PAB",'symbol' =>  "B/."),
        array('id' =>93, 'country' => "Paraguay",'currencies' =>  "Guarani",'code' =>  "PYG",'symbol' =>  "Gs"),
        array('id' =>94, 'country' => "Peru", 'currencies' => "Nuevos Soles",'code' =>  "PEN",'symbol' =>  "S/."),
        array('id' =>95, 'country' => "Philippines",'currencies' =>  "Pesos",'code' =>  "PHP",'symbol' =>  "Php"),
        array('id' =>96, 'country' => "Poland",'currencies' =>  "Zlotych",'code' =>  "PLN",'symbol' =>  "zł"),
        array('id' =>97, 'country' => "Qatar",'currencies' =>  "Rials",'code' =>  "QAR",'symbol' =>  "﷼"),
        array('id' =>98, 'country' => "Romania",'currencies' =>  "New Lei",'code' =>  "RON", 'symbol' =>  "lei"),
        array('id' =>99, 'country' => "Russia", 'currencies' => "Rubles",'code' =>  "RUB",'symbol' =>  "руб"),
        array('id' =>100, 'country' => "Saint Helena",'currencies' =>  "Pounds",'code' =>  "SHP",'symbol' =>  "£"),
        array('id' =>101, 'country' => "Saudi Arabia",'currencies' =>  "Riyals",'code' =>  "SAR",'symbol' =>  "﷼"),
        array('id' =>102, 'country' => "Serbia",'currencies' =>  "Dinars", 'code' =>  "RSD",'symbol' =>  "Дин."),
        array('id' =>103, 'country' => "Seychelles",'currencies' =>  "Rupees",'code' =>  "SCR",'symbol' =>  "₨"),
        array('id' =>104, 'country' => "Singapore",'currencies' =>  "Dollars",'code' =>  "SGD",'symbol' =>  "$"),
        array('id' =>105, 'country' => "Slovenia",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>106, 'country' => "Solomon Islands",'currencies' =>  "Dollars",'code' =>  "SBD",'symbol' =>  "$"),
        array('id' =>107, 'country' => "Somalia",'currencies' =>  "Shillings",'code' =>  "SOS",'symbol' =>  "S"),
        array('id' =>108, 'country' => "South Africa",'currencies' =>  "Rand",'code' =>  "ZAR",'symbol' =>  "R"),
        array('id' =>109, 'country' => "South Korea",'currencies' =>  "Won",'code' =>  "KRW", 'symbol' =>  "₩"),
        array('id' =>110, 'country' => "Spain",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>111, 'country' => "Sri Lanka",'currencies' =>  "Rupees",'code' =>  "LKR",'symbol' =>  "₨"),
        array('id' =>112, 'country' => "Sweden",'currencies' =>  "Kronor",'code' =>  "SEK",'symbol' =>  "kr"),
        array('id' =>113, 'country' => "Switzerland",'currencies' =>  "Francs",'code' =>  "CHF",'symbol' =>  "CHF"),
        array('id' =>114, 'country' => "Suriname",'currencies' =>  "Dollars",'code' =>  "SRD",'symbol' =>  "$"),
        array('id' =>115, 'country' => "Syria",'currencies' =>  "Pounds",'code' =>  "SYP",'symbol' =>  "£"),
        array('id' =>116, 'country' => "Taiwan",'currencies' =>  "New Dollars",'code' =>  "TWD",'symbol' =>  "NT$"),
        array('id' =>117, 'country' => "Thailand",'currencies' =>  "Baht",'code' =>  "THB",'symbol' =>  "฿"),
        array('id' =>118, 'country' => "Trinidad and Tobago",'currencies' =>  "Dollars",'code' =>  "TTD",'symbol' =>  "TT$"),
        array('id' =>119, 'country' => "Turkey",'currencies' =>  "Lira",'code' =>  "TRY",'symbol' =>  "TL"),
        array('id' =>120, 'country' => "Turkey",'currencies' =>  "Liras",'code' =>  "TRL",'symbol' =>  "£"),
        array('id' =>121, 'country' => "Tuvalu",'currencies' =>  "Dollars",'code' =>  "TVD",'symbol' =>  "$"),
        array('id' =>122, 'country' => "Ukraine",'currencies' =>  "Hryvnia",'code' =>  "UAH",'symbol' =>  "₴"),
        array('id' =>123, 'country' => "United Kingdom",'currencies' =>  "Pounds",'code' =>  "GBP",'symbol' =>  "£"),
        array('id' =>124, 'country' => "United States of America",'currencies' =>  "Dollars",'code' =>  "USD",'symbol' =>  "$"),
        array('id' =>125, 'country' => "Uruguay",'currencies' =>  "Pesos",'code' =>  "UYU",'symbol' =>  '$U'),
        array('id' =>126, 'country' => "Uzbekistan",'currencies' =>  "Sums",'code' =>  "UZS", 'symbol' =>  "лв"),
        array('id' =>127, 'country' => "Vatican City",'currencies' =>  "Euro",'code' =>  "EUR",'symbol' =>  "€"),
        array('id' =>128, 'country' => "Venezuela",'currencies' =>  "Bolivares Fuertes",'code' =>  "VEF",'symbol' =>  "Bs"),
        array('id' =>129, 'country' => "Vietnam", 'currencies' => "Dong",'code' =>  "VND",'symbol' =>  "₫"),
        array('id' =>130, 'country' => "Yemen",'currencies' =>  "Rials",'code' =>  "YER",'symbol' =>  "﷼"),
        array('id' =>131, 'country' => "Zimbabwe",'currencies' =>  "Zimbabwe Dollars",'code' =>  "ZWD",'symbol' =>  "Z$"),
        array('id' =>132, 'country' => "India",'currencies' =>  "Rupees",'code' =>  "INR",'symbol' =>  '₹'),
    );
    Currency::insert($Currency);
    }
}
