<?php

use Illuminate\Database\Seeder;
use App\Setting;
use Carbon\Carbon;
use App\SiteMeta;

class SiteMetaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SiteMeta::truncate();
    
        $SiteMetaData = [

            [  
                'user_id' => '1', 
                'page_name' => 'Continue Watching List',
                'page_slug' => 'continue-watching-list',
                'page_title' => 'Continue Watching List',
                'meta_description' => 'Continue Watching List',
                'meta_keyword' => 'Continue Watching List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Latest Videos',
                'page_slug' => 'latest-videos',
                'page_title' => 'Latest Videos',
                'meta_description' => 'Latest Videos',
                'meta_keyword' => 'Latest Videos',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Language List',
                'page_slug' => 'language-list',
                'page_title' => 'Language List',
                'meta_description' => 'Language List',
                'meta_keyword' => 'Language List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Most Watched Videos',
                'page_slug' => 'Most-watched-videos',
                'page_title' => 'Most Watched Videos',
                'meta_description' => 'Most Watched Videos',
                'meta_keyword' => 'Most Watched Videos',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Most Watched Videos Country',
                'page_slug' => 'Most-watched-videos-country',
                'page_title' => 'Most Watched Videos Country',
                'meta_description' => 'Most Watched Videos Country',
                'meta_keyword' => 'Most Watched Videos Country',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Most Watched Videos Site',
                'page_slug' => 'Most-watched-videos-site',
                'page_title' => 'Most Watched Videos Site',
                'meta_description' => 'Most Watched Videos Site',
                'meta_keyword' => 'Most Watched Videos Site',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],

            [  'user_id' => '1', 
                'page_name' => 'Home',
                'page_slug' => 'home',
                'page_title' => 'Home',
                'meta_description' => 'Home',
                'meta_keyword' => 'Home',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            
            [  'user_id' => '1', 
                'page_name' => 'Category List',
                'page_slug' => 'categoryList',
                'page_title' => 'Category List',
                'meta_description' => 'Category List',
                'meta_keyword' => 'Category List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],

            [  'user_id' => '1', 
                'page_name' => 'Audio category List',
                'page_slug' => 'AudiocategoryList',
                'page_title' => 'Audio category List',
                'meta_description' => 'Audio category List',
                'meta_keyword' => 'Audio category List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Series category List',
                'page_slug' => 'SeriescategoryList',
                'page_title' => 'Series category List',
                'meta_description' => 'Series category List',
                'meta_keyword' => 'Series category List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],

            [  'user_id' => '1', 
                'page_name' => 'Category Live',
                'page_slug' => 'CategoryLive',
                'page_title' => 'Category Live',
                'meta_description' => 'Category Live',
                'meta_keyword' => 'Category Live',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Artist List',
                'page_slug' => 'artist-list',
                'page_title' => 'Artist List',
                'meta_description' => 'Artist List',
                'meta_keyword' => 'Artist List',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Channel List',
                'page_slug' => 'Channel-list',
                'page_title' => 'Channel-list',
                'meta_description' => 'Channel-list',
                'meta_keyword' => 'Channel-list',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Content Partners',
                'page_slug' => 'content-partners',
                'page_title' => 'Content Partners',
                'meta_description' => 'Content Partners',
                'meta_keyword' => 'Content Partners',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Reset Password',
                'page_slug' => 'Reset-Password',
                'page_title' => 'Reset Password',
                'meta_description' => 'Reset Password',
                'meta_keyword' => 'Reset Password',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Login',
                'page_slug' => 'login',
                'page_title' => 'Login',
                'meta_description' => 'Login',
                'meta_keyword' => 'Login',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Signup',
                'page_slug' => 'signup',
                'page_title' => 'Signup',
                'meta_description' => 'Signup',
                'meta_keyword' => 'Signup',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Upgrade Subscription Plan',
                'page_slug' => 'upgrade-subscription_plan',
                'page_title' => 'Upgrade Subscription Plan',
                'meta_description' => 'Upgrade Subscription Plan',
                'meta_keyword' => 'Upgrade Subscription Plan',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'My Profile',
                'page_slug' => 'myprofile',
                'page_title' => 'My Profile',
                'meta_description' => 'My Profile',
                'meta_keyword' => 'My Profile',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Transactiondetails',
                'page_slug' => 'transactiondetails',
                'page_title' => 'Transactiondetails',
                'meta_description' => 'Transactiondetails',
                'meta_keyword' => 'Transactiondetails',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],

            [  'user_id' => '1', 
                'page_name' => 'My Wishlists',
                'page_slug' => 'mywishlists',
                'page_title' => 'My Wishlists',
                'meta_description' => 'My Wishlists',
                'meta_keyword' => 'My Wishlists',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [  'user_id' => '1', 
                'page_name' => 'Watchlater',
                'page_slug' => 'watchlater',
                'page_title' => 'Watchlater',
                'meta_description' => 'Watchlater',
                'meta_keyword' => 'Watchlater',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
        ];

        SiteMeta::insert($SiteMetaData);
    }
}
